# Generated by Django 6.0.6 on 2026-07-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpielerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Spieler',
                'verbose_name_plural': 'Spieler',
                'ordering': ['spiel', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SpielModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rundenanzahl', models.IntegerField()),
                ('angelegt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spiel',
                'verbose_name_plural': 'Spiele',
                'ordering': ['-angelegt_am'],
            },
        ),
        migrations.CreateModel(
            name='RundeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rundennummer', models.PositiveSmallIntegerField()),
                ('reizwert', models.IntegerField()),
                ('rundenausgang', models.CharField(choices=[('gewonnenes Spiel', 'gewonnenes Spiel'), ('doppeltes Abgehen', 'doppeltes Abgehen'), ('einfaches Abgehen', 'einfaches Abgehen'), ('Tausender gewonnen', 'Tausender gewonnen'), ('Tausender verloren', 'Tausender verloren')], max_length=20)),
                ('spielmacher_punkte', models.IntegerField(default=0)),
                ('verlustwert', models.IntegerField(default=0)),
                ('mitpunkte_pro_gegenspieler', models.IntegerField(default=0)),
                ('spielmacher_stern', models.BooleanField(default=False)),
                ('gegenspieler_stern', models.BooleanField(default=False)),
                ('geber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geber_runden', to='scoring.spielermodel')),
                ('spielmacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spielmacher_runden', to='scoring.spielermodel')),
                ('spiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runden', to='scoring.spielmodel')),
            ],
            options={
                'verbose_name': 'Runde',
                'verbose_name_plural': 'Runden',
                'ordering': ['spiel', 'rundennummer'],
            },
        ),
        migrations.AddField(
            model_name='spielermodel',
            name='spiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spieler', to='scoring.spielmodel'),
        ),
        migrations.CreateModel(
            name='GegenspielerRundeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meldepunkte', models.IntegerField(default=0)),
                ('stichwerte', models.IntegerField(default=0)),
                ('hat_eigenen_stich', models.BooleanField(default=False)),
                ('runde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gegenspieler', to='scoring.rundemodel')),
                ('spieler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gegenspieler_runden', to='scoring.spielermodel')),
            ],
            options={
                'verbose_name': 'Gegenspieler-Runde',
                'verbose_name_plural': 'Gegenspieler-Runden',
                'ordering': ['runde', 'spieler__position'],
                'constraints': [models.UniqueConstraint(fields=('runde', 'spieler'), name='unique_spieler_pro_runde')],
            },
        ),
        migrations.AddConstraint(
            model_name='spielermodel',
            constraint=models.UniqueConstraint(fields=('spiel', 'position'), name='unique_spieler_position_pro_spiel'),
        ),
        migrations.AddConstraint(
            model_name='rundemodel',
            constraint=models.UniqueConstraint(fields=('spiel', 'rundennummer'), name='unique_rundennummer_pro_spiel'),
        ),
    ]
