# Generated by Django 6.0.6 on 2026-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundemodel',
            name='spielmacher_meldepunkte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rundemodel',
            name='spielmacher_stichwerte',
            field=models.IntegerField(default=0),
        ),
    ]
