"""
Django settings for binokel_tracker project.

Generated by 'django-admin startproject' using Django 6.0.6.

Konfiguration folgt dem 12-Factor-App-Prinzip: alle umgebungsabhängigen Werte
werden aus Umgebungsvariablen gelesen. Standardwerte sind für lokale Entwicklung
geeignet und dürfen in Production niemals unverändert übernommen werden.

Pflicht-Env-Variablen in Production:
    DJANGO_SECRET_KEY          — sicherer, zufälliger Schlüssel (kein Insecure-Default!)
    DJANGO_DEBUG               — muss auf 'False' gesetzt sein
    DJANGO_ALLOWED_HOSTS       — kommagetrennte Liste erlaubter Hostnamen

Optionale Env-Variablen:
    DJANGO_DB_PATH             — Pfad zur SQLite-Datei (Standard: backend/db.sqlite3)
    DJANGO_STATIC_ROOT         — Pfad für collectstatic (Standard: backend/staticfiles)
    DJANGO_CSRF_TRUSTED_ORIGINS — kommagetrennte HTTPS-Origins (z. B. https://example.com)

Deployment-Checklist: python manage.py check --deploy

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Konfiguration über Umgebungsvariablen ─────────────────────────────────────

# SECURITY WARNING: keep the secret key used in production secret!
# In Production muss DJANGO_SECRET_KEY auf einen sicheren Wert gesetzt sein.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-9d5i)$qvzb(=7ur!%^n&s1s=25+^q+6y!c75q^0x-@)2xj7f)6',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Akzeptierte Wahrheitswerte (Groß-/Kleinschreibung egal): true, 1, yes, on
# Alle anderen Werte (z. B. false, 0, no, off) setzen DEBUG=False.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes', 'on')

_allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Projektspezifische Apps
    'scoring',
    # BDD-Testinfrastruktur
    'behave_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'binokel_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'binokel_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Im Testbetrieb (behave, pytest): Datenbank im Arbeitsspeicher.
        # In Production: Pfad über DJANGO_DB_PATH setzen (außerhalb des Repo-Verzeichnisses).
        # Im Entwicklungsbetrieb: Datei db.sqlite3 im backend/-Verzeichnis
        'NAME': Path(os.environ.get('DJANGO_DB_PATH', str(BASE_DIR / 'db.sqlite3'))),
        'TEST': {
            'NAME': ':memory:',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles')))


# ── Production-Sicherheitseinstellungen ───────────────────────────────────────
# Werden nur aktiviert wenn DEBUG=False gesetzt ist.

_csrf_trusted_origins_raw = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_origins_raw.split(',') if o.strip()]

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
