"""
Django settings for binokel_tracker project.

Generated by 'django-admin startproject' using Django 6.0.6.

Konfiguration folgt dem 12-Factor-App-Prinzip: alle umgebungsabhängigen Werte
werden aus Umgebungsvariablen gelesen. Standardwerte sind für lokale Entwicklung
geeignet und dürfen in Production niemals unverändert übernommen werden.

Pflicht-Env-Variablen in Production:
    DJANGO_SECRET_KEY          — sicherer, zufälliger Schlüssel (kein Insecure-Default!)
    DJANGO_DEBUG               — muss auf 'False' gesetzt sein
    DJANGO_ALLOWED_HOSTS       — kommagetrennte Liste erlaubter Hostnamen

Optionale Env-Variablen:
    DJANGO_DB_PATH             — Pfad zur SQLite-Datei (Standard: backend/db.sqlite3)
    DJANGO_STATIC_ROOT         — Pfad für collectstatic (Standard: backend/staticfiles)
    DJANGO_CSRF_TRUSTED_ORIGINS — kommagetrennte HTTPS-Origins (z. B. https://example.com)

Deployment-Checklist: python manage.py check --deploy

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Konfiguration über Umgebungsvariablen ─────────────────────────────────────

# SECURITY WARNING: keep the secret key used in production secret!
# In Production muss DJANGO_SECRET_KEY auf einen sicheren Wert gesetzt sein.
# Der Insecure-Default erlaubt nur die lokale Entwicklung (DEBUG=True); bei DEBUG=False
# wird sein Einsatz weiter unten hart unterbunden (fail-safe statt fail-open).
_INSECURE_SECRET_KEY = 'django-insecure-9d5i)$qvzb(=7ur!%^n&s1s=25+^q+6y!c75q^0x-@)2xj7f)6'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Akzeptierte Wahrheitswerte (Groß-/Kleinschreibung egal): true, 1, yes, on
# Alle anderen Werte (z. B. false, 0, no, off) setzen DEBUG=False.
# Default 'True' hält lokale Entwicklung/Tests bequem; Production MUSS DJANGO_DEBUG=False
# setzen (im env-Template verankert). Bei DEBUG=False greift zusätzlich der SECRET_KEY-
# Riegel unten, sodass ein vergessenes/falsches Setup nicht still fail-open läuft.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes', 'on')

_allowed_hosts_raw = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()]
# localhost/127.0.0.1 immer erlauben: Der Deployment-Healthcheck ruft den
# Endpunkt lokal auf der VM als http://localhost/health/ auf.
for _local_host in ('localhost', '127.0.0.1'):
    if _local_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_local_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Projektspezifische Apps
    'scoring',
    # BDD-Testinfrastruktur
    'behave_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'binokel_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'binokel_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Im Testbetrieb (behave, pytest): Datenbank im Arbeitsspeicher.
        # In Production: Pfad über DJANGO_DB_PATH setzen (außerhalb des Repo-Verzeichnisses).
        # Im Entwicklungsbetrieb: Datei db.sqlite3 im backend/-Verzeichnis
        'NAME': Path(os.environ.get('DJANGO_DB_PATH', str(BASE_DIR / 'db.sqlite3'))),
        'TEST': {
            'NAME': ':memory:',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles')))


# ── Production-Sicherheitseinstellungen ───────────────────────────────────────
# Werden nur aktiviert wenn DEBUG=False gesetzt ist.

_csrf_trusted_origins_raw = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_origins_raw.split(',') if o.strip()]

if not DEBUG:
    # SICHERHEITSRIEGEL (fail-safe): In Production darf niemals der öffentlich im Repo
    # stehende Insecure-Default-Key verwendet werden. Fehlt DJANGO_SECRET_KEY (env nicht
    # gesourct, Tippfehler, leere Variable), bräche Django sonst still mit kompromittierbaren
    # Session-/CSRF-/Signing-Tokens hoch. Deshalb hart abbrechen.
    if SECRET_KEY == _INSECURE_SECRET_KEY:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY ist nicht gesetzt oder verwendet den Insecure-Default, '
            'obwohl DEBUG=False ist. In Production einen sicheren, zufälligen Schlüssel setzen '
            '(z. B. `python -c "from django.core.management.utils import get_random_secret_key; '
            'print(get_random_secret_key())"`).'
        )

    # Gunicorn spricht per UNIX-Socket HTTP mit Nginx; ohne diesen Header wäre
    # request.is_secure() immer False und SECURE_SSL_REDIRECT würde jede – auch
    # bereits über HTTPS eingelieferte – Anfrage erneut umleiten (Redirect-Loop).
    # Nginx setzt X-Forwarded-Proto im Proxy-Block.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    # Der lokale Healthcheck (http://localhost/health/) wird über HTTP aufgerufen
    # und darf nicht auf HTTPS umgeleitet werden, sonst schlägt der Deploy-Check fehl.
    SECURE_REDIRECT_EXEMPT = [r'^health/$']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Referrer-Policy explizit setzen, damit App-Antworten (von Django) und statische
    # Dateien (Header von Nginx im /static/-Block) denselben Wert liefern. Ohne dies
    # sendete Django den Default 'same-origin', Nginx 'strict-origin-when-cross-origin'
    # – zwei widersprüchliche Werte über dieselbe Domain (siehe ENG-004, E2).
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
